### ISSUE TITLE
ValueError: could not convert string to float: '[10,16,18,20,22]'

### ISSUE THREAD

**Issue by ckbs1973** [Matin114/hass-goecharger-victron-automation#2]
Leider komme ich mit folgender Fehlermeldung nicht weiter. Würde mich über eine Ünterstützung sehr freuen.
Gruß Christian

`Logger: homeassistant
Quelle: components/sensor/__init__.py:670
Erstmals aufgetreten: 11:32:06 (56 Vorkommnisse)
Zuletzt protokolliert: 11:59:32

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 663, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '[10,16,18,20,22]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 666, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: '[10,16,18,20,22]'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1010, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 963, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1113, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1050, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 670, in state
    raise ValueError(
ValueError: Sensor sensor.go_echarger_203563_clp has device class 'current', state class 'measurement' unit 'A' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '[10,16,18,20,22]' (<class 'str'>)
`

**Comment by Matin114** [comment]
Hallo, dieser konkrete Fehler sollte jetzt in der Betaversion 0.0.3.1 gefixed sein. 
Da habe ich das originale Feld "CLP" mit seinem Array Wert auf 5 einzelne Integer Werte aufgetrennt.

Sollte es beim Einrichten irgendwelche weiteren Probleme geben, kann ich gerne so gut wie möglich helfen.
Da das Projekt aktuell noch in Arbeit ist, wurde die Dokumentation leider auch vernachlässigt, das sollte sich aber hoffentlich in Zukunft ändern.

Gruß, Martin

**Comment by ckbs1973** [comment]
Hallo Martin. In der Anleituzng steht, das PGRID immer negativ sein muss um ein Überschussladen zu starten. Der Wert "Power from Grid (from ids) zeigt aber bei Einspeisung (also Überschuss) immer einen positiven Wert an. Wie kann ich den Wert in der ändern bzw. die Funktion anpassen?
Gruß Christian

**Comment by ckbs1973** [comment]
Hallo Martin. Soweit funktioniert jetzt die Automation. Was schlussendlich nicht funktioniert ist, dass der Ladestrom individuell zum Überschuss angehoben oder abgesenkt wird. Mir ist dabei aufgefallen, dass die Entität "Load balancing available current" ausgegraut und somit nicht belegt bzw. berechnet wird. Steuert diese Entität den tatsächlichen Ladestrom?
Was ebenfalls komisch ist, dass direkt mit der Ladung über drei Phasen begonnen wird, obwohl der Überschuss nicht ausreichend vorhanden ist dafür. Nach ein paar Minuten wird dann auf einphasiges Laden umgeschaltet. 
Gruß Christian

**Comment by Matin114** [comment]
Hallo Christian, ich vermute mal, Sie versuchen das Überschussladen vom GO-E Charger selbst zu nutzten. Leider habe ich damit keine Erfahrung, da ich die Logik dafür selbst geschrieben habe.
Diese Automatisierung basiert auf einem System mit Hausakku und einem Victron Energy management (wobei andere mit ähnlichem Aufwand auch funktionieren sollten). 
Aktuell bin ich an der Dokumentation wie man das Projekt richtig einrichtet, und hoffe heute den Großteil zu schaffen, aber zu dem GO-E internen Überschussladen kann ich leider nichts aussagen.

**Comment by ckbs1973** [comment]
Schade. Genau das ist mein Ziel. Gerade der go-echarger ist bei vielen so beliebt, da er viele dieser Möglichkeiten möglich machen würde. Wer könnte denn hier weiterhelfen?

**Comment by Matin114** [comment]
Das originale Repository, bei dem nur der GO-E in Home Assistant integriert wurde ist hier: https://github.com/syssi/homeassistant-goecharger-mqtt
Denke das wäre eine Anlaufstelle, ansonsten weiß ich dazu leider auch nichts.

**Comment by ckbs1973** [comment]
Super. Vielen Dank.
